#!/bin/bash
[ -z "$LSOPTS" ] && LSOPTS='-h --color=auto'
alias ls=" ls $LSOPTS"
alias l='ls -l'
alias la='ls -Al'
alias lx='ls -lX'
alias lt='ls -lt'
alias lm='ls -l | more'

alias cl=' clear; l'
alias cls=' clear; ls'

alias grep='grep --color=auto'

alias fg=' fg'

if [ command -v nocorrect > /dev/null 2>&1 ]; then
  alias cp='nocorrect cp -i'
  alias mv='nocorrect mv -i'
  alias mkdir='nocorrect mkdir'
else
  alias cp='cp -i'
  alias mv='mv -i'
  alias mkdir='mkdir'
fi

alias md='mkdir -p'
alias rd='rmdir'
md () { mkdir -p $1; cd $1; }

alias which='type -a'
alias .='popd'
alias d='dirs -v | head -10'
alias path='echo -e ${PATH//:/\\n}'
alias du='du -sh'

alias crontab='VIM_CRONTAB=true crontab'
alias mvim='gvim'
alias nev='nvim'
alias nevs='nvim -S Session.vim'
alias vims='vim -S Session.vim'

function sudoedit() {
  SUDO_COMMAND="sudoedit $@" command sudoedit "$@"
}

alias please='sudo'

alias np='noglob numpy'

alias wget='noglob wget'

# When the first argument is modified (TARGET), run the rest of the args as cmd
# onmodify dissertation.md pandoc dissertation.md dissertation.pdf
# TODO: check for options (-l, -c, etc)

alias tls='tmux ls'
alias tns='tmux new -s'
alias tat='tmux attach -t'
function tnp() {
if cd ~/Projects/$1; then
  tmux new-session -A -s $1
fi
}

alias gst='git status'
alias cst='clear; git status'
alias gsh='git stash'
alias gshl='git stash show -p'
alias gpl='git pull'
alias gpu='git push'
alias gad='git add'
alias gau='git add --update'
alias gd='git diff'
alias gwd='git diff --color-words'
alias grh='git reset HEAD --'
alias gci='git commit -v'
alias gcim='git commit -m'
alias gcall='git commit -v -a'
alias gbr='git branch'
alias gbra='git branch -a'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcot='git checkout -t'
alias gcotb='git checkout --track -b'
alias glo='git log --all --oneline --decorate --graph -n 20'
