#!/bin/bash
[ -z "$LSOPTS" ] && LSOPTS='-h --color=auto'
alias ls=" ls $LSOPTS"
alias l='ls -l'
alias la='ls -Al'
alias lx='ls -lX'
alias lt='ls -lt'
alias lm='ls -l | more'

alias cl=' clear; l'
alias cls=' clear; ls'

alias grep='grep --color=auto'

alias fg=' fg'

if [ command -v nocorrect > /dev/null 2>&1 ]; then
  alias cp='nocorrect cp -i'
  alias mv='nocorrect mv -i'
  alias mkdir='nocorrect mkdir'
else
  alias cp='cp -i'
  alias mv='mv -i'
  alias mkdir='mkdir'
fi

alias md='mkdir -p'
alias rd='rmdir'
mcd () { mkdir -p $1; cd $1; }

alias which='type -a'
alias .='popd'
alias d='dirs -v | head -10'
alias path='echo -e ${PATH//:/\\n}'
alias du='du -sh'

alias crontab='VIM_CRONTAB=true crontab'
alias mvim='gvim'
alias nev='nvim'
alias nevs='nvim -S Session.vim'
alias vims='vim -S Session.vim'

function sudoedit() {
  SUDO_COMMAND="sudoedit $@" command sudoedit "$@"
}

alias please='sudo'

function numpy() {
pyscript="
from numpy import *
out = "$@"
try:
  print(*out, sep='\n')
except:
  print(out)
"
python -c $pyscript
}
alias np='noglob numpy'

# When the first argument is modified (TARGET), run the rest of the args as cmd
# onmodify dissertation.md pandoc dissertation.md dissertation.pdf
onmodify() {
  TARGET=${1:-.}; shift
  CMD="$@"

  echo "$TARGET" "$CMD"
  while inotifywait --exclude '.git' -qq -r -e close_write,moved_to,move_self $TARGET; do
    sleep 0.2
    bash -c "$CMD"
    echo
  done
}

# TODO: check for options (-l, -c, etc)
wccl() {
  wc -l $@ | cut -f1 -d' '
}

alias tls='tmux ls'
alias tns='tmux new -s'
alias tat='tmux attach -t'
function tnp() {
if cd ~/Projects/$1; then
  tmux new-session -A -s $1
fi
}

alias gst='git status'
alias cst='clear; git status'
alias gsh='git stash'
alias gshl='git stash show -p'
alias gpl='git pull'
alias gpu='git push'
alias gad='git add'
alias gau='git add --update'
alias gd='git diff'
alias gwd='git diff --color-words'
alias grh='git reset HEAD --'
alias gci='git commit -v'
alias gcim='git commit -m'
alias gcall='git commit -v -a'
alias gbr='git branch'
alias gbra='git branch -a'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcot='git checkout -t'
alias gcotb='git checkout --track -b'
alias glo='git log -n 5'
alias glog='git log'
alias glogp='git log --pretty=format:"%h %s" --graph'

# vim: ft=sh
