#!/usr/bin/zsh

CONF_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}

source $HOME/.profile
source $CONF_HOME/zsh/zshrc

function tmux_session_name() {
  for s in $(tmux list-sessions -F '#{session_name}'); do
    tmux list-panes -F '#{pane_tty} #{session_name}' -t "$s"
  done | grep "$(tty)" | awk '{print $2}' 2> /dev/null
}


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# <<< conda initialize <<<

if pgrep tmux &> /dev/null; then
  conda activate $(tmux_session_name) &> /dev/null
else
  [ -t 0 ] && command -v setup_tmux_sessions &> /dev/null && setup_tmux_sessions
fi
