" obsolete in nvim
set nocompatible
set history=10000       " welp
filetype plugin on      " allow plugins
filetype indent on      " auto indenting

set runtimepath+=~/.config/vim

" Other
let &viewdir=$HOME.'/.local/share/vim/view'

" Set up plugins, non nvim go here, shared plugins go in the plugins.vim
call plug#begin('~/.config/vim/plugged')
source ~/.config/vim/plugins.vim
call plug#end()

" Section: modular configs
runtime! config/*.vim
runtime! config/plugins/*.vim
runtime! local.vim

