set nocompatible
set history=10000       " welp
set t_Co=256 " sloppy, lazy. fix pls


let $CFGDIR=empty($XDG_CONFIG_HOME) ? $HOME.'/.config/vim' : $XDG_CONFIG_HOME.'/vim'
set runtimepath+=$CFGDIR

let $DATADIR=empty($XDG_DATA_HOME) ? $HOME.'/.local/share/vim' : $XDG_DATA_HOME.'/vim'
let &viewdir=$DATADIR.'/view'

runtime shared.vim
runtime plugins.vim
runtime local.vim
